Custom_User_Settings/urls.py
from django.urls import path
from Custom_User_Settings import views

app_name = "Custom_User_Settings"

urlpatterns = [
    path("settings/", views.CreateSettingsView.as_view(), name="settings"),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from users import views as users_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", TemplateView.as_view(template_name="home.html"), name="home2"),
    path(
        "team/",
        TemplateView.as_view(template_name="team.html"),
        name="team",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="about.html"),
        name="about",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="terms_conditions.html"),
        name="terms",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="feedback.html"),
        name="feedback",
    ),
    path(
        "pricing/",
        TemplateView.as_view(template_name="pricing.html"),
        name="pricing",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("accounts/", include("user_profile.urls")),
    path("", include("Custom_User_Settings.urls")),
    path("", include("SavedUserTemplates.urls")),
]

urlpatterns += [
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="allauth/account/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="allauth/account/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="allauth/account/login.html"),
        name="login",
    ),
    path(
        "accounts/signup/",
        users_views.SignUpView.as_view(template_name="allauth/account/signup.html"),
        name="signup",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="allauth/account/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="allauth/account/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="allauth/account/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="allauth/account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("", include("toolpage.urls")),
    path("", include("Custom_User_Settings.urls", namespace="list-settings")),
]

urlpatterns += [
    path("", include("SavedUserTemplates.urls", namespace="SavedUserTemplate")),
]

# Allauth
urlpatterns += [
    path("accounts/", include("allauth.urls")),
]

toolpage/urls.py
from django.urls import path
from toolpage import views as toolpage_views

app_name = "toolpage"

urlpatterns = [
    path(
        "toolpage_app/", toolpage_views.ToolpageAppView.as_view(), name="toolpage_app"
    ),
    path(
        "toolpage_update/",
        toolpage_views.ToolpageTemplateUpdate.as_view(),
        name="toolpage_template_update",
    ),
    path(
        "reshape/",
        toolpage_views.ReshapeText,
        name="toolpage_reshape",
    ),
    path(
        "readfile/",
        toolpage_views.readfile,
        name="toolpage_readfile",
    ),
    path(
        "transcribe_audio/",
        toolpage_views.transcribe_audio,
        name="toolpage_transcribe_audio",
    ),
]

user_profile/urls.py
"""User profile app URL."""

from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UserProfileDetailView.as_view(), name="profile_detail"),
    path(
        "profile/update/", views.UserProfileDetailView.as_view(), name="profile_update"
    ),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('customer-portal/', views.CreateCustomerPortalSessionView.as_view(), name='customer_portal'),
    path('webhook/stripe/', csrf_exempt(views.StripeWebhookView.as_view()), name='stripe_webhook'),
]

users/urls.py
"""Accounts app URL Configuration."""

from django.urls import path

from users import views as users_views
from . import views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.SignUpView.as_view(success_url="/toolpage_app/"),
        name="signup",
    ),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
]

users/models.py
"""Accounts models."""

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class CustomUser(AbstractUser):
    """A custom User model.

    Arguments:
    ---------
    AbstractUser : class
        Django's `AbstractUser` class.

    Returns:
    -------
    object:
        `CustomUser` model.

    """

    username = models.CharField(
        _("Username"), unique=False, default="Aluminotes User", max_length=32
    )
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self) -> str:
        """Get the string representation of the object.

        Returns:
        -------
        str
            The unique identifier of the model, `email`.

        """
        return self.email

users/forms.py
"""Forms for accounts app."""

from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """Registration form."""

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-lg",
                "type": "password",
                "placeholder": "Password",
            }
        ),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control form-control-lg",
                "type": "password",
                "placeholder": "Re-Enter Password",
            }
        ),
    )

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")
        widgets = {
            "first_name": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "First Name",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "class": "form-control form-control-lg",
                    "placeholder": "Last Name",
                }
            ),
            "email": forms.EmailInput(
                attrs={"class": "form-control form-control-lg", "placeholder": "Email"}
            ),
        }


class CustomUserChangeForm(UserChangeForm):
    """User profile change view."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("first_name", "last_name", "email")

users/views.py
"""Accounts view."""

from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import CustomUserCreationForm
from users.models import CustomUser

from django.contrib import messages

from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage

from .tokens import account_activation_token


class SignUpView(CreateView):
    """User registration view."""

    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = "allauth/account/signup.html"
    success_url = reverse_lazy("/toolpage_app")
    extra_context = {"title_text": "Sign Up", "button_text": "Register"}

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save(commit=False)
        user.isactive = False
        user.save()
        mail_subject = "Activate your user account."
        message = render_to_string(
            "activate_account.html",
            {
                "user": user.username,
                "domain": get_current_site(self.request).domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
                "protocol": "https" if self.request.is_secure() else "http",
            },
        )
        email = EmailMessage(mail_subject, message, to=[user.email])
        if not (email.send()):
            messages.error(
                self.request,
                f"Problem sending confirmation email to {user.email}, check if you typed it correctly.",
            )
        else:
            messages.success(
                self.request,
                "Sign up successful. Please check your email to activate your account.",
            )

        # Redirect to login page
        return redirect(self.get_success_url())


def activate(request, uidb64, token):
    User = CustomUser
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(
            request,
            "Thank you for your email confirmation. Now you can login your account.",
        )
        return redirect("login")
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect("homepage")

users/templates/about.html
{% extends "landing_style.html" %}
{% load static %}
{% block title %}
{% endblock title %}
{% block content %}
    <div class="about-title">about</div>
    <div class="about-style">
        <div class="about-top-block">
            <h2>welcome to aluminotes!</h2>
            <p>
                For students and professionals facing challenges in note-taking,
                Aluminotes provides an AI-powered solution to enhance text organization
                and lead to improvements in users' writings.
                Unlike baseline AI tools like ChatGPT, our software offers personalized formatting options
                with the ability to customize outputs to cater to user needs,
                setting a new standard for efficiency and quality in digital writing.
            </p>
            <h2>designed with you in mind</h2>
            <p>
                Aluminotes was formed from the shared struggle of students
                who experienced difficulties with writing and managing notes under
                tight schedules, and an understanding for peers who find their own
                writing assignments to be lacking. Aluminotes is made
                to aid students and career professionals who desire improvements in their
                notes, reports, articles, presentations, and more.
            </p>
            <h2>access and benefits</h2>
            <p>
                Aluminotes can be accessed immediately by any user with an account.
                Users who purchase a subscription plan will experience Aluminotes with all additional
                accessibility features, more feedback options, and access to community tools to
                develop and share their own note-taking templates!
            </p>
            <h2>contact us</h2>
            <div class="row mt-4">
                <div class="col-md-2">
                    <h3>
                        <i class="fa-solid fa-envelope"> </i> Email Us
                    </h3>
                    <p>aluminotes@gmail.com</p>
                </div>
            </div>
            <a class="btn bloodbackground_button_1 btn-lg center_button_right mb-5"
               href="{% url 'terms' %}"
               role="button">Terms & Conditions</a>
        </div>
    </div>
{% endblock content %}

users/templates/activate_account.html
{% autoescape off %}
    Hey {{ user.username }},
    Please click on the link below to confirm your registration:
    http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
    See you in a bit!
    - The Aluminotes Team
{% endautoescape %}

users/templates/base_generic.html
{# Load the tag library #}
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="us-en">
    <head>
        <style>@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap');</style>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <meta charset="UTF-8" />
        <meta name="description" content="Aluminotes" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="John Doe" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'img/favicon.ico' %}" />
        <title>Aluminotes</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        {% block style %}
        {% endblock style %}
        {% if user.is_authenticated %}
            {% if user.custom_user_settings.theme == "galactic_blood" %}
                <link rel="stylesheet" href="{% static 'css/galactic_blood.css' %}" />
            {% elif user.custom_user_settings.theme == "pink" %}
                <link rel="stylesheet" href="{% static 'css/pink.css' %}" />
            {% elif user.custom_user_settings.theme == "void" %}
                <link rel="stylesheet" href="{% static 'css/void.css' %}" />
            {% endif %}
        {% else %}
            <link rel="stylesheet" href="{% static 'css/galactic_blood.css' %}" />
        {% endif %}
        <link href="{% static 'fontawesomefree/css/all.min.css' %}"
              rel="stylesheet"
              type="text/css" />
    </head>
    {% block body_start %}
        <body class="theme">
        {% endblock body_start %}
        {% include "navbar.html" %}
        {% block overcontent %}
            {% comment %} Overcontent added for more customizability {% endcomment %}
            <div class="container">
                <h1 class="text-center fw-bold mb-5">
                    {% block title %}
                    {% endblock title %}
                </h1>
                <div>
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        {% endblock overcontent %}
        <!--{% include "footer.html" %}-->
    </body>
</html>

users/templates/feedback.html
{% extends "landing_style.html" %}
{% load static %}
{% block title %}
{% endblock title %}
{% block content %}
    <div class="feedback row justify-content-center">
        <div class="background col-md-8 col-lg-6 d-flex mb-5 justify-content-center">
            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdUAYAODRC-sA8ZS9XMhaPtDz822v_bZP04MmU4ZYmqZTB6UA/viewform?embedded=true"
                    width="100%"
                    frameborder="0"
                    marginheight="0"
                    marginwidth="0"
                    scrolling="yes">Loading…</iframe>
        </div>
    </div>
{% endblock content %}

users/templates/footer.html
<footer class="footer pt-3 mt-4 text-muted">
    <div class="container">
        Django Project template is powered by
        <a target="_blank" href="https://getbootstrap.com/">Bootstrap</a>
        and
        <a target="_blank" href="https://fontawesome.com/">Font awesome</a>.
    </div>
</footer>

users/templates/generic_create_update_form.html
{% extends "landing_style.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {{ title_text }}
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post"
                  enctype="multipart/form-data"
                  class="form-slider-slipper">
                <!-- If you're looking for something that is messing up the CSS on this page,
                the previous line's class is probably it.  -->
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.media }}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-light btn-lg px-5">{{ button_text }}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

users/templates/home.html
{% extends "landing_style.html" %}
{% block overcontent %}
    {% load static %}
    <div class="container mobile-center">
        <img src="{% static 'img/logoHome.png' %}"
             alt="The aluminotes logo"
             height="600px"
             width="auto"
             class="homelogo right-align">
        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="left-align rounded-3">
            <div>
                <h1 class="display-3 titleText fw-bold">reshape your notes</h1>
                <p class="visionText">
                    aluminotes is an AI-assisted text formatter, editor, and all-round improver, with options to help make your notes shine.
                </p>
                <p class="visionText mb-5">
                    using advanced prompts and intensive ai knowledge, aluminotes can help you read, write, and format your ideas to improve clarity, conciseness, and aesthetic.
                </p>
                <p class="col-md-8 fs-4">
                    <div class="center_button">
                        <a class="btn bloodbackground_button_1 btn-lg left-align"
                           href="{% url 'toolpage:toolpage_app' %}"
                           id="try_aluminotes"
                           role="button">try aluminotes</a>
                        {% if not request.user.is_authenticated %}
                            <a class="btn bloodbackground_button_1 btn-lg center_button_right"
                               style="min-width:100px;
                                      margin-left:10px"
                               href="{% url 'login' %}"
                               role="button">log in</a>
                            <a class="btn bloodbackground_button_1 btn-lg center_button_right"
                               id="home_signup_button"
                               href="{% url 'signup' %}"
                               role="button">sign up</a>
                        {% endif %}
                    </div>
                </p>
            </div>
        </div>
    </div>
{% endblock overcontent %}

users/templates/landing_style.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/landing.css' %}" />
{% endblock style %}

users/templates/navbar.html
{% load django_bootstrap5 %}
{% load static %}
{% load navbar_clean_username %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $(window).scroll(function () {
            if ($(this).scrollTop() > 50) { // Change this value to adjust when the navbar changes
                $('.navbar').addClass('navbar-solid');
            } else {
                $('.navbar').removeClass('navbar-solid');
            }
        });
    });
</script>
<nav class="navbar navbar-expand-md navbar-dark fixed-top justify-content-center">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "img/logoTiny.png" %}" height="40px" width="auto" alt="aluminotes">
            aluminotes
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar_wrapper"
             id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'toolpage:toolpage_app' %}">use aluminotes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">about</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'team' %}">team</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pricing' %}">pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'feedback' %}">feedback</a>
                </li>
            </ul>
            <div class="nav-item navbar-collapse collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <div class="dropdown">
                            <a class="nav-link nav-item dropdown-toggle"
                               role="button"
                               data-toggle="dropdown"
                               data-bs-toggle="dropdown"
                               aria-expanded="false">{{ user.email|clean_username }}</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{% url 'user_profile:profile_detail' %}">
                                        <i class="fa-solid fa-user-cog"></i> Account
                                    </a>
                                </li>
                                <li>
                                    <div class="dropdown-divider"></div>
                                </li>
                                <li>
                                    <div class="dropdown-item">
                                        <form id="frm_logout" method="post" action="{% url 'logout' %}">
                                            {% csrf_token %}
                                            <i class="fa-solid fa-sign-out-alt"></i> <a class="logout" href="javascript:$('#frm_logout').submit();">Log out</a>
                                        </form>
                                    </div>
                                </li>
                                <li>
                                    <div class="dropdown-divider"></div>
                                </li>
                                <li>
                                    <a class="dropdown-item"
                                       href="{% url 'Custom_User_Settings:settings' %}">
                                        <i class="fa-solid fa-gear pl-2"></i> Settings
                                    </a>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">
                                <i class="fa-solid fa-arrow-right-to-bracket"></i>  log in </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:signup' %}">
                                <i class="fa-solid fa-user-plus"></i>  sign up </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>

users/templates/password_reset_done.html
{% extends "landing_style.html" %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="alert alert-info" role="alert">
            We've emailed you instructions for setting your password. If they haven't
            arrived in a few minutes, check your spam folder.
        </div>
    </div>
{% endblock content %}

users/templates/pricing.html
{% extends "landing_style.html" %}
{% block content %}
  <div class="pricing-container">
    <h1 class="pricing-title">Effective Writing Begins With a Plan</h1>
    <h1 class="pricing-subtitle">Reach new heights by writing without boundaries</h1>
    <h2>All premium plans include:</h2>
    <div class="icons-container">
      <div class="row">
        <div class="col">
          <i class="fa-solid fa-align-left size"></i>
          <br>
          Summarizer
        </div>
        <div class="col">
          <i class="fa-solid fa-indent size"></i>
          <br>
          Formatter
        </div>
        <div class="col">
          <i class="fa-solid fa-volume-high size"></i>
          <br>
          Text to Speech
        </div>
        <div class="col">
          <i class="fa-solid fa-microphone size"></i>
          <br>
          Speech Recognition
        </div>
        <div class="col">
          <i class="fa-solid fa-eye size"></i>
          <br>
          Bionic Reading
        </div>
        <div class="col">
          <i class="fa-solid fa-bookmark size"></i>
          <br>
          Templates
        </div>
      </div>
    </div>
  </div>
  <div class="card-container">
    <div class="row mobile_column">
      <div class="col px-lg-3">
        <div class="bloodbackground_box_shadow">
          <h1 class="pricing">Free</h1>
          <p class="pricing">For individuals just getting started with aluminotes</p>
          <p class="price">
            $0<span>no credit card needed</span>
          </p>
          <hr>
          <ul class="checkmark">
            <li>Limited to 500 words of input text</li>
            <li>Access to summarization tool</li>
            <li>Limited to formal tone tool</li>
            <li>Study notes, meeting notes, and outline formatting tool</li>
            <li>Access to text-to-speech tool</li>
            <li>Access to bionic reading tool</li>
          </ul>
          {% if user.is_authenticated %}
            <a class="btn bloodbackground_button_3 btn-lg center_button_left"
               href="{% url 'toolpage:toolpage_app' %}"
               role="button">Start Now</a>
          {% else %}
            <a class="btn bloodbackground_button_3 btn-lg center_button_left"
               href="{% url 'signup' %}"
               role="button">Start Now</a>
          {% endif %}
        </div>
      </div>
      <div class="col px-lg-3">
        <div class="bloodbackground_box_shadow">
          <h1 class="pricing">Premium</h1>
          <p class="pricing">For users looking to amplify their productivity</p>
          <p class="price">
            $5<span>billed monthly</span>
          </p>
          <hr>
          <ul class="checkmark">
            <li>Unlimited input text size</li>
            <li>Access to all summarization and formatting styles and tools</li>
            <li>Access to text-to-speech tool</li>
            <li>Access to speech-to-text tool</li>
            <li>Access to bionic reading tool</li>
            <li>Access to revision history</li>
            <li>Ability to save preferences</li>
            <li>Access to custom formatting settings</li>
            <li>Access to custom organization settings</li>
            <li>Access to community templates</li>
          </ul>
          {% if user.is_authenticated and user.userprofile.user_type == 0 and not user.userprofile.stripe_customer_id %}
            {% csrf_token %}
            <button id="checkout-button"
                    class="btn bloodbackground_button_4 btn-lg center_button_left">Start Now</button>
          {% elif user.userprofile.user_type == 0 or user.userprofile.user_type == 1 %}
            <form action="{% url 'user_profile:customer_portal' %}" method="post">
              {% csrf_token %}
              <button type="submit"
                      class="btn bloodbackground_button_4 btn-lg center_button_left">Start Now</button>
            </form>
          {% else %}
            <a class="btn bloodbackground_button_4 btn-lg center_button_left"
               href="{% url 'signup' %}"
               role="button">Start Now</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>
  <script type="text/javascript">
  var stripe = Stripe('pk_test_51POSEVCwhdqZcwfyw74RFwzFgmBDYO6HrmQYhSwKgYroAul9wGyXnYVsZ8fiezUsS0qVHFI9SXRmC7rRizQ5Mvxf00zpKlCCt7');

    document.getElementById('checkout-button').addEventListener('click', function () {
        fetch("{% url 'user_profile:create_checkout_session' %}", {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
        })
        .then(response => response.json())
        .then(session => {
            return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
            if (result.error) {
                alert(result.error.message);
            }
        })
        .catch(function (error) {
            console.error('Error:', error);
        });
    });
  </script>
{% endblock content %}

users/templates/settings_crud_style.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/settings_crud.css' %}" />
{% endblock style %}