django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from users import views as users_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", TemplateView.as_view(template_name="home.html"), name="home2"),
    path(
        "team/",
        TemplateView.as_view(template_name="team.html"),
        name="team",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="about.html"),
        name="about",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="terms_conditions.html"),
        name="terms",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="feedback.html"),
        name="feedback",
    ),
    path(
        "pricing/",
        TemplateView.as_view(template_name="pricing.html"),
        name="pricing",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("accounts/", include("user_profile.urls")),
    path("", include("Custom_User_Settings.urls")),
    path("", include("SavedUserTemplates.urls")),
]

urlpatterns += [
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="allauth/account/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="allauth/account/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="allauth/account/login.html"),
        name="login",
    ),
    path(
        "accounts/signup/",
        users_views.SignUpView.as_view(template_name="allauth/account/signup.html"),
        name="signup",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="allauth/account/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="allauth/account/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="allauth/account/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="allauth/account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("", include("toolpage.urls")),
    path("", include("Custom_User_Settings.urls", namespace="list-settings")),
]

urlpatterns += [
    path("", include("SavedUserTemplates.urls", namespace="SavedUserTemplate")),
]

# Allauth
urlpatterns += [
    path("accounts/", include("allauth.urls")),
]

user_profile/urls.py
"""User profile app URL."""

from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UserProfileDetailView.as_view(), name="profile_detail"),
    path(
        "profile/update/", views.UserProfileDetailView.as_view(), name="profile_update"
    ),
    path('delete-account/', views.delete_account, name='delete_account'),
    path('create-checkout-session/', views.CreateCheckoutSessionView.as_view(), name='create_checkout_session'),
    path('customer-portal/', views.CreateCustomerPortalSessionView.as_view(), name='customer_portal'),
    path('webhook/stripe/', csrf_exempt(views.StripeWebhookView.as_view()), name='stripe_webhook'),
]

users/urls.py
"""Accounts app URL Configuration."""

from django.urls import path

from users import views as users_views
from . import views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.SignUpView.as_view(success_url="/toolpage_app/"),
        name="signup",
    ),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
]

user_profile/models.py
"""User profile app models."""

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone

from users.models import CustomUser


class UserProfile(models.Model):
    """UserProfile model class."""

    class Gender(models.IntegerChoices):
        """Gender choice class."""

        NONE = 0
        FEMALE = 1
        MALE = 2
        OTHER = 3

    class UserType(models.IntegerChoices):
        """User Type Choice"""

        FREE = 0
        PREMIUM = 1

    custom_user = models.OneToOneField("users.CustomUser", on_delete=models.CASCADE)
    gender = models.IntegerField(choices=Gender.choices, default=Gender.NONE)
    age = models.IntegerField(default=21)
    picture = models.ImageField(upload_to="profile_pictures/", blank=True)
    user_type = models.IntegerField(choices=UserType.choices, default=UserType.FREE)
    phone = models.CharField(max_length=20, blank=True)
    last_prompt_time = models.DateTimeField(default=timezone.now)
    last_file_upload_time = models.DateTimeField(default=timezone.now)
    stripe_customer_id = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self) -> str:
        """Return a string representation of SavedUserTemplate"""
        return str(self.custom_user)


@receiver(post_save, sender=CustomUser)
def create_profile(sender, instance, created, **kwargs):
    """Create an object of UserProfile when a user CustomUser object is created."""
    if sender and created:
        UserProfile.objects.create(custom_user=instance)


post_save.connect(create_profile, sender=CustomUser)

user_profile/forms.py
"""User Profile Forms."""

from django import forms

from . import models


class UserProfileUpdateForm(forms.ModelForm):
    """User profile change view."""

    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=32)

    class Meta:
        """Meta class."""

        model = models.UserProfile
        fields = ["first_name", "last_name", "picture"]

user_profile/views.py
import stripe
from django.conf import settings
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View, generic
from django.views.decorators.csrf import csrf_protect

from .forms import UserProfileUpdateForm
from .models import UserProfile


class UserProfileDetailView(LoginRequiredMixin, generic.DetailView):
    """Profile detail and update view."""

    model = UserProfile
    template_name = "user_profile/userprofile_detail.html"
    slug_field = None
    slug_url_kwarg = ""

    def get_object(self, queryset=None):
        """Retrieve the UserProfile of the current user."""
        return self.model.objects.get(custom_user=self.request.user)

    @method_decorator(login_required)
    @method_decorator(csrf_protect)
    def post(self, request, *args, **kwargs):
        """Handle form submission for updating user profile or deleting account."""
        user_profile = self.get_object()

        if "action" in request.POST:
            if request.POST.get("action") == "confirm-delete":
                if user_profile.custom_user != request.user:
                    # Just in case -- prevent other users from deleting your account
                    raise PermissionDenied("Cannot delete another user's profile.")
                user_profile.custom_user.delete()  # Delete the custom user
                logout(request)  # Log out the user
                return redirect("home")  # Redirect to home page

        form = UserProfileUpdateForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.custom_user = self.request.user
            user_profile.save()
            request.user.first_name = form.cleaned_data["first_name"]
            request.user.last_name = form.cleaned_data["last_name"]
            request.user.save()
            return redirect("user_profile:profile_detail")
        return self.get(request, form=form)

    def get(self, request, *args, **kwargs):
        """Render the profile detail and update form."""
        user_profile = self.get_object()
        form = UserProfileUpdateForm(
            instance=user_profile,
            initial={
                "first_name": request.user.first_name,
                "last_name": request.user.last_name,
            },
        )
        return render(
            request, self.template_name, {"form": form, "user_profile": user_profile}
        )

def delete_account(request):
    # Get the user profile
    user_profile = request.user.userprofile
    customer_id = user_profile.stripe_customer_id

    if customer_id:
        # Cancel all subscriptions for the customer
        subscriptions = stripe.Subscription.list(customer=customer_id)
        for subscription in subscriptions.auto_paging_iter():
            stripe.Subscription.delete(subscription.id)

        # Delete the Stripe customer
        stripe.Customer.delete(customer_id)

    # Delete the user profile and user account
    request.user.delete()

    # Redirect to home or another page
    return redirect('home')

stripe.api_key = settings.STRIPE_SECRET_KEY

class CreateCheckoutSessionView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        YOUR_DOMAIN = "http://127.0.0.1:8000"

        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                    'price': 'price_1PsZjPCwhdqZcwfy8lY4EFxC',
                    'quantity': 1,
                },
            ],
            mode='subscription',
            success_url=YOUR_DOMAIN + reverse('user_profile:profile_detail'),
            cancel_url=YOUR_DOMAIN + reverse('user_profile:profile_detail'),
            metadata={
                'user_id': request.user.id,  # Storing the user's ID in metadata
            }
        )

        return JsonResponse({
            'id': checkout_session.id,
            'checkout_url': checkout_session.url
        })

class StripeWebhookView(View):
    def post(self, request, *args, **kwargs):
        payload = request.body
        sig_header = request.META['HTTP_STRIPE_SIGNATURE']
        event = None

        try:
            event = stripe.Webhook.construct_event(
                payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
            )
        except ValueError:
            # Invalid payload
            return HttpResponse(status=400)
        except stripe.error.SignatureVerificationError:
            # Invalid signature
            return HttpResponse(status=400)

        # Handle checkout session event
        if event['type'] == 'checkout.session.completed':
            session = event['data']['object']
            # Update the user's profile to Premium
            handle_checkout_session(session)

        # Handle subscription updated event
        if event['type'] == 'customer.subscription.updated':
            subscription = event['data']['object']  # Subscription object
            handle_subscription_update(subscription)

        # Handle subscription deletion or payment failure events
        if event['type'] == 'customer.subscription.deleted':
            subscription = event['data']['object']  # Contains the subscription object
            handle_subscription_cancellation(subscription)

        elif event['type'] == 'invoice.payment_failed':
            invoice = event['data']['object']  # Contains the invoice object
            handle_payment_failure(invoice)

        return HttpResponse(status=200)

def handle_checkout_session(session):
    # You can retrieve the user information from session['metadata'] if you stored it when creating the session
    # For example, assuming you stored the user ID in metadata:
    user_id = session.get('metadata', {}).get('user_id')
    customer_id = session.get('customer')

    # Debugging print statements
    print(f"Received Stripe session: {session}")
    print(f"Extracted user_id from metadata: {user_id}")

    if user_id:
        try:
            # Retrieve the corresponding UserProfile
            user_profile = UserProfile.objects.get(custom_user__id=user_id)
            print(f"Found UserProfile: {user_profile}")

            # Update the UserProfile to Premium
            user_profile.user_type = UserProfile.UserType.PREMIUM
            # Store the Stripe customer ID in the user's profile
            user_profile.stripe_customer_id = customer_id
            user_profile.save()
            print(f"Updated UserProfile to PREMIUM for user_id: {user_id}")
            print(f"Updated UserProfile with Stripe customer_id: {customer_id} for user_id: {user_id}")

        except UserProfile.DoesNotExist:
            # Print an error if the UserProfile does not exist
            print(f"Error: UserProfile not found for user_id: {user_id}")
    else:
        # Print an error if user_id is not found in the metadata
        print("Error: No user_id found in session metadata")

def handle_subscription_cancellation(subscription):
    # Retrieve the user ID from metadata stored during checkout session creation
    customer_id = subscription.get('customer')

    # Find the corresponding user profile based on the Stripe customer ID
    try:
        user_profile = UserProfile.objects.get(stripe_customer_id=customer_id)
        print(f"Found UserProfile: {user_profile}")
        # Update the user type to "Free"
        user_profile.user_type = UserProfile.UserType.FREE
        user_profile.save()

        print(f"Updated UserProfile to FREE for customer_id: {customer_id}")
    except UserProfile.DoesNotExist:
        print(f"UserProfile not found for customer_id: {customer_id}")

def handle_subscription_update(subscription):
    # Get the user ID from metadata (if stored)
    customer_id = subscription.get('customer')
    try:
        # Find the user profile with the matching user ID
        user_profile = UserProfile.objects.get(stripe_customer_id=customer_id)
        print(f"Found UserProfile: {user_profile}")

        # Get the subscription status & data
        subscription_data = subscription.get('items', {}).get('data', [])
        status = subscription.get('status')

        # Get Product ID
        for item in subscription_data:
            plan = item.get('plan', {})
            product_id = plan.get('product')

        print(f"PRODUCT: {product_id}")

        # Update user type based on subscription status
        if product_id == 'prod_Qk3r1jtusnFf8h':
            if status == 'active':
                user_profile.user_type = UserProfile.UserType.PREMIUM
        elif product_id == 'prod_QqSKjOlNpcSDdW':
            if status == 'active':
                user_profile.user_type = UserProfile.UserType.FREE

        user_profile.save()

        print(f"Updated UserProfile to {user_profile.user_type} for UserProfile: {user_profile}")
    except UserProfile.DoesNotExist:
        print(f"UserProfile not found for customer_id: {customer_id}")


def handle_payment_failure(invoice):
    customer_id = invoice.get('customer')

    try:
        user_profile = UserProfile.objects.get(stripe_customer_id=customer_id)
        # You could handle any custom logic here, such as sending reminders or warnings
        # Update the user type to "Free"
        user_profile.user_type = UserProfile.UserType.FREE
        user_profile.save()
        print(f"Payment failed for user: {user_profile.custom_user.email}")
    except UserProfile.DoesNotExist:

user_profile/templates/user_profile/delete_user.html
{% extends "settings_crud_style.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {{ title_text }}
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                {{ form }}
                <button type="submit" name="action" value="confirm" class="btn btn-danger">Confirm</button>
                <button type="submit" name="action" value="go_back" class="btn btn-secondary">Go Back</button>
            </form>
        </div>
    </div>
{% endblock content %}

user_profile/templates/user_profile/userprofile_detail.html
{% extends "settings_crud_style.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
{% endblock title %}
{% block content %}
    <div class="container-xl px-4 mt-4">
        <div class="row justify-content-center">
            <div class="col-xl-8 ">
                <!-- Account details card-->
                <div class="card mb-4">
                    <div class="card-header">Account Details</div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- Form Row-->
                            <div class="row gx-3 mb-3">
                                <!-- Form Group (first name)-->
                                <div class="col-md-6">
                                    <label class="small mb-1" for="name">First Name</label>
                                    <input class="form-control"
                                           id="id_first_name"
                                           type="first_name"
                                           name="first_name"
                                           placeholder="First Name"
                                           value="{{ user.first_name }}"
                                           disabled>
                                </div>
                                <!-- Form Group (last name)-->
                                <div class="col-md-6">
                                    <label class="small mb-1" for="name">Last Name</label>
                                    <input class="form-control"
                                           id="id_last_name"
                                           type="last_name"
                                           name="last_name"
                                           placeholder="Last Name"
                                           value="{{ user.last_name }}"
                                           disabled>
                                </div>
                            </div>
                            <!-- Form Group (email address)-->
                            <div class="mb-3">
                                <label class="small mb-1" for="id_email">Email address</label>
                                <input class="form-control"
                                       id="id_email"
                                       type="email"
                                       name="email"
                                       placeholder="Enter your email address"
                                       value="{{ user.email }}"
                                       disabled>
                            </div>
                            <!-- Form Group (email address)-->
                            <div class="mb-3">
                                <label class="small mb-1" for="plans">User Plan</label>
                                <input class="form-control"
                                       id="id_plan"
                                       type="user_type"
                                       name="user_type"
                                       value="{% if user.userprofile.user_type == 0 %} Free {% elif user.userprofile.user_type == 1 %} Premium {% endif %}"
                                       disabled>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- Additional Actions -->
                <div class="card mb-4">
                    <div class="card-header">Actions</div>
                    <div class="card-body">
                        <div class="row mobile_column">
                            <div class="col-4 text-center p-1">
                                {% if user.userprofile.user_type == 0 and not user.userprofile.stripe_customer_id %}
                                    {% csrf_token %}
                                    <button id="checkout-button" class="btn btn-secondary profile-button">
                                        <i class="fa-regular fa-credit-card"></i> Upgrade to Premium
                                    </button>
                                {% elif user.userprofile.user_type == 0 %}
                                    <form action="{% url 'user_profile:customer_portal' %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-secondary profile-button">
                                            <i class="fa-regular fa-credit-card"></i> Upgrade to Premium
                                        </button>
                                    </form>
                                {% elif user.userprofile.user_type == 1 %}
                                    <form action="{% url 'user_profile:customer_portal' %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-secondary profile-button">
                                            <i class="fa-solid fa-ban"></i> Cancel Subscription
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            <div class="col-4 text-center p-1">
                                <a class="btn btn-secondary profile-button"
                                   role="button"
                                   data-toggle="modal"
                                   data-target="#deleteAccountModal">
                                    <i class="fa-solid fa-user-slash"></i> Delete Account
                                </a>
                            </div>
                            <div class="col-4 text-center p-1">
                                <a class="btn btn-secondary profile-button"
                                   role="button"
                                   href="{% url 'password_change' %}">
                                    <i class="fa-solid fa-lock"></i> Change Password
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Account Modal -->
    <div class="modal fade"
         id="deleteAccountModal"
         tabindex="-1"
         aria-labelledby="deleteAccountModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteAccountModalLabel">Are you sure you want to delete your account?</h5>
                </div>
                <div class="modal-body">
                    Deleting your account will remove all your information from our database. This cannot be undone.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <form method="post"
                          id="deleteAccountForm"
                          action="{% url 'user_profile:delete_account' %}">
                        {% csrf_token %}
                        <button type="submit"
                                name="action"
                                value="confirm-delete"
                                class="btn btn-danger">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
    var stripe = Stripe('pk_test_51POSEVCwhdqZcwfyw74RFwzFgmBDYO6HrmQYhSwKgYroAul9wGyXnYVsZ8fiezUsS0qVHFI9SXRmC7rRizQ5Mvxf00zpKlCCt7');

    document.getElementById('checkout-button').addEventListener('click', function () {
        fetch("{% url 'user_profile:create_checkout_session' %}", {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
            },
        })
        .then(response => response.json())
        .then(session => {
            return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
            if (result.error) {
                alert(result.error.message);
            }
        })
        .catch(function (error) {
            console.error('Error:', error);
        });
    });
    </script>
{% endblock content %}