SavedUserTemplates/urls.py
from django.urls import path

from SavedUserTemplates import views

app_name = "SavedUserTemplates"
urlpatterns = [
    path(
        "templates/create", views.CreateTemplateView.as_view(), name="create-template"
    ),  # Create
    path(
        "templates/", views.TemplateListView.as_view(), name="list-templates"
    ),  # Read, list
    path(
        "templates/<int:pk>/detail",
        views.TemplateDetailView.as_view(),
        name="template-detail",
    ),  # Read, detail
    path(
        "templates/<int:pk>/update",
        views.TemplateUpdateView.as_view(),
        name="update-template",
    ),  # Update
    path(
        "templates/<int:pk>/delete",
        views.TemplateDeleteView.as_view(),
        name="delete-template",
    ),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from users import views as users_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", TemplateView.as_view(template_name="home.html"), name="home2"),
    path(
        "team/",
        TemplateView.as_view(template_name="team.html"),
        name="team",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="about.html"),
        name="about",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="terms_conditions.html"),
        name="terms",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="feedback.html"),
        name="feedback",
    ),
    path(
        "pricing/",
        TemplateView.as_view(template_name="pricing.html"),
        name="pricing",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("accounts/", include("user_profile.urls")),
    path("", include("Custom_User_Settings.urls")),
    path("", include("SavedUserTemplates.urls")),
]

urlpatterns += [
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="allauth/account/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="allauth/account/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="allauth/account/login.html"),
        name="login",
    ),
    path(
        "accounts/signup/",
        users_views.SignUpView.as_view(template_name="allauth/account/signup.html"),
        name="signup",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="allauth/account/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="allauth/account/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="allauth/account/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="allauth/account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("", include("toolpage.urls")),
    path("", include("Custom_User_Settings.urls", namespace="list-settings")),
]

urlpatterns += [
    path("", include("SavedUserTemplates.urls", namespace="SavedUserTemplate")),
]

# Allauth
urlpatterns += [
    path("accounts/", include("allauth.urls")),
]

toolpage/urls.py
from django.urls import path
from toolpage import views as toolpage_views

app_name = "toolpage"

urlpatterns = [
    path(
        "toolpage_app/", toolpage_views.ToolpageAppView.as_view(), name="toolpage_app"
    ),
    path(
        "toolpage_update/",
        toolpage_views.ToolpageTemplateUpdate.as_view(),
        name="toolpage_template_update",
    ),
    path(
        "reshape/",
        toolpage_views.ReshapeText,
        name="toolpage_reshape",
    ),
    path(
        "readfile/",
        toolpage_views.readfile,
        name="toolpage_readfile",
    ),
    path(
        "transcribe_audio/",
        toolpage_views.transcribe_audio,
        name="toolpage_transcribe_audio",
    ),
]

users/urls.py
"""Accounts app URL Configuration."""

from django.urls import path

from users import views as users_views
from . import views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.SignUpView.as_view(success_url="/toolpage_app/"),
        name="signup",
    ),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
]

SavedUserTemplates/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class SavedUserTemplate(models.Model):
    # Custom_user model connected in 1 to many with SavedUserTemplates
    author = models.ForeignKey("users.CustomUser", on_delete=models.CASCADE)
    name_of_template = models.CharField(max_length=200, unique=True)
    summary = models.BooleanField(default=False)
    formal = models.BooleanField(default=False)
    academic = models.BooleanField(default=False)
    creative = models.BooleanField(default=False)
    study_notes = models.BooleanField(default=False)
    meeting_notes = models.BooleanField(default=False)
    email_and_memo = models.BooleanField(default=False)
    outline = models.BooleanField(default=False)
    story_telling = models.BooleanField(default=False)
    research_paper = models.BooleanField(default=False)
    report = models.BooleanField(default=False)
    resume = models.BooleanField(default=False)

    def __str__(self) -> str:
        """Return a string representation of SavedUserTemplate"""
        return str(self.name_of_template)

SavedUserTemplates/views.py
from django.urls import reverse_lazy
from django.views import generic

from user_profile import mixins as user_mixins

from . import models

# Create your views here.


class CreateTemplateView(user_mixins.PremiumRequiredMixin, generic.CreateView):
    """View to create template."""

    model = models.SavedUserTemplate
    fields = [
        "name_of_template",
        "summary",
        "formal",
        "academic",
        "creative",
        "study_notes",
        "meeting_notes",
        "email_and_memo",
        "outline",
        "story_telling",
        "research_paper",
        "report",
        "resume",
    ]
    success_url = reverse_lazy("SavedUserTemplates:list-templates")
    extra_context = {"title_text": "Create Template", "button_text": "Create"}

    def form_valid(self, form):
        """Set the author of the current template to the user currently logged in."""
        form.instance.author = self.request.user
        return super().form_valid(form)


class TemplateListView(user_mixins.PremiumRequiredMixin, generic.ListView):
    """Template list view."""

    model = models.SavedUserTemplate
    # queryset = models.SavedUserTemplate.objects

    def get_queryset(self):
        """Return the list of items for this view. Only list the templates that belong to the user currently logged in."""
        # Assuming 'author' is a ForeignKey to the User model
        return self.model.objects.filter(author=self.request.user)


class TemplateDetailView(user_mixins.PremiumRequiredMixin, generic.DetailView):
    """Detail view of SavedUserTemplates."""

    model = models.SavedUserTemplate


class TemplateUpdateView(user_mixins.PremiumRequiredMixin, generic.UpdateView):
    """View to update template."""

    model = models.SavedUserTemplate
    fields = [
        "name_of_template",
        "summary",
        "formal",
        "academic",
        "creative",
        "study_notes",
        "meeting_notes",
        "email_and_memo",
        "outline",
        "story_telling",
        "research_paper",
        "report",
        "resume",
    ]
    success_url = reverse_lazy("SavedUserTemplates:list-templates")
    extra_context = {"title_text": "Edit Template", "button_text": "Save"}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["template"] = self.object if self.object else None
        return context


class TemplateDeleteView(user_mixins.PremiumRequiredMixin, generic.DeleteView):
    """View to delete template."""

    # Note to self:
    #

    model = models.SavedUserTemplate
    success_url = reverse_lazy("SavedUserTemplate:list-templates")
    template_name = "SavedUserTemplates/savedusertemplate_delete.html"
    extra_context = {"title_text": "Delete Template"}

SavedUserTemplates/templates/SavedUserTemplates/savedusertemplate_delete.html
{% extends "settings_crud_style.html" %}
{% block content %}
    <div class="template-detail-back-button row justify-content-center">
        <a type="back"
           class="back-button px-5"
           role="button"
           href="{% url 'SavedUserTemplates:list-templates' %}">
            <i class="fa-solid fa-arrow-left-long"></i> Back
        </a>
    </div>
    <div class="d-flex justify-content-center templates-detail">
        <div class="row">
            <div class="col-md-4">
                <div class="card reset-password-custom delete_template_container text-white mt-2 ">
                    <div class="card-body p-5 ">
                        <div class="mt-md-4">
                            <h2 class="fw-bold mb-5 text-uppercase text-center templates-title">Delete {{ object.name_of_template }}</h2>
                            <form method="post">
                                {% csrf_token %}
                                <p class="text-center">Are you sure you want to delete "{{ object }}"?</p>
                                <input type="submit"
                                       value="Confirm"
                                       class="btn btn-outline-light mt-md-5 btn-lg px-5">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

SavedUserTemplates/templates/SavedUserTemplates/savedusertemplate_detail.html
{% extends "settings_crud_style.html" %}
{% block title %}
{% endblock title %}
{% block content %}
       <div class="template-detail-back-button row justify-content-center">
              <a type="back"
                 class="back-button px-5"
                 role="button"
                 href="{% url 'SavedUserTemplates:list-templates' %}">
                     <i class="fa-solid fa-arrow-left-long"></i> Back
              </a>
       </div>
       <div class="d-flex justify-content-center templates-detail">
              <div class="row">
                     <div class="col-md-4">
                            <div class="card reset-password-custom text-white mt-2 ">
                                   <div class="card-body p-5">
                                          <div class="mb-md-5 mt-md-4 pb-5">
                                                 <h2 class="fw-bold mb-5 text-uppercase text-center templates-title">{{ object.name_of_template }}</h2>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.summary %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Summary</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.formal %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Formal</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.academic %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Academic</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.creative %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Creative</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.study_notes %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Study Notes</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.meeting_notes %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">
                                                               Meeting Notes
                                                        </label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.email_and_memo %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">
                                                               Email and Memo
                                                        </label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.outline %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Outline</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.story_telling %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">
                                                               Story Telling
                                                        </label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.research_paper %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">
                                                               Research Paper
                                                        </label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.report %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label"
                                                               for="flexSwitchCheckCheckedDisabled">Report</label>
                                                 </div>
                                                 <div class="switch-margin form-check form-switch">
                                                        <input class="form-check-input"
                                                               type="checkbox"
                                                               role="switch"
                                                               id="flexSwitchCheckCheckedDisabled"
                                                               {% if object.resume %}checked disabled{% else %}disabled{% endif %}>
                                                        <label class="form-check-label custom-label" for="flexSwitchCheckDefault">Resume</label>
                                                 </div>
                                                 <div class="text-center mt-4">
                                                        <a class="btn btn-outline-light btn-lg px-5"
                                                           href="{% url 'SavedUserTemplates:update-template' object.id %}">Edit</a>
                                                        <a class="btn btn-outline-light btn-lg px-5"
                                                           href="{% url 'SavedUserTemplates:delete-template' object.id %}">Delete</a>
                                                 </div>
                                          </div>
                                   </div>
                            </div>
                     </div>
              </div>
       </div>
{% endblock content %}

SavedUserTemplates/templates/SavedUserTemplates/savedusertemplate_list.html
{% extends "settings_crud_style.html" %}
{% block title %}
{% endblock title %}
{% block content %}
    <div class="template-list-back-button">
        <a type="back"
           class="back-button px-5"
           role="button"
           href="{% url 'toolpage:toolpage_app' %}">
            <i class="fa-solid fa-arrow-left-long"></i> Back
        </a>
    </div>
    <div class="">
        <div class="card template-detail text-white">
            <div class="card-body p-5 text-center">
                <div class="mb-md-5 mt-md-4 pb-5">
                    <h2 class="fw-bold mb-4 text-uppercase">Available Templates</h2>
                    <div class="row template-list">
                        {% if object_list %}
                            <ol>
                                {% for template in object_list %}
                                    <li>
                                        <a class=" btn template-list-button btn-lg"
                                           href="{% url 'SavedUserTemplates:template-detail' template.id %}">
                                            {{ template.name_of_template }}
                                        </a>
                                        {% comment %} {{ template.name_of_template }} {% endcomment %}
                                    </li>
                                {% endfor %}
                            </ol>
                        {% else %}
                            <p>No templates are available.</p>
                        {% endif %}
                    </div>
                    <div class="row justify-content-center template-detail-buttons mt-3">
                        <div class="">
                            <div class="text-center">
                                {% comment %} {% if user.is_authenticated and user.userprofile.is_teacher %}
                                    <a class="btn btn-warning" href="{% url 'polls:create-question' %}">
                                        <i class="fa-solid fa-plus"></i> Create Question
                                    </a>
                                {% endif %}
                                {% if user.is_authenticated and user.userprofile.is_student %}
                                    <a class="btn btn-warning disabled" href="{% url 'polls:create-question' %}" role="button" aria-disabled="true">
                                        <i class="fa-solid fa-plus"></i> Create Question
                                    </a>
                                {% endif %} {% endcomment %}
                                {% if user.is_authenticated %}
                                    <a class="btn btn-outline-light btn-lg px-5"
                                       href="{% url 'SavedUserTemplates:create-template' %}">Create Template</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}