SavedUserTemplates/urls.py
from django.urls import path

from SavedUserTemplates import views

app_name = "SavedUserTemplates"
urlpatterns = [
    path(
        "templates/create", views.CreateTemplateView.as_view(), name="create-template"
    ),  # Create
    path(
        "templates/", views.TemplateListView.as_view(), name="list-templates"
    ),  # Read, list
    path(
        "templates/<int:pk>/detail",
        views.TemplateDetailView.as_view(),
        name="template-detail",
    ),  # Read, detail
    path(
        "templates/<int:pk>/update",
        views.TemplateUpdateView.as_view(),
        name="update-template",
    ),  # Update
    path(
        "templates/<int:pk>/delete",
        views.TemplateDeleteView.as_view(),
        name="delete-template",
    ),
]

django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from users import views as users_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", TemplateView.as_view(template_name="home.html"), name="home2"),
    path(
        "team/",
        TemplateView.as_view(template_name="team.html"),
        name="team",
    ),
    path(
        "about/",
        TemplateView.as_view(template_name="about.html"),
        name="about",
    ),
    path(
        "terms/",
        TemplateView.as_view(template_name="terms_conditions.html"),
        name="terms",
    ),
    path(
        "feedback/",
        TemplateView.as_view(template_name="feedback.html"),
        name="feedback",
    ),
    path(
        "pricing/",
        TemplateView.as_view(template_name="pricing.html"),
        name="pricing",
    ),
    path("accounts/", include("users.urls", namespace="users")),
    path("accounts/", include("user_profile.urls")),
    path("", include("Custom_User_Settings.urls")),
    path("", include("SavedUserTemplates.urls")),
]

urlpatterns += [
    path(
        "accounts/password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="allauth/account/password_change.html"
        ),
        name="password_change",
    ),
    path(
        "accounts/password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="allauth/account/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/login/",
        auth_views.LoginView.as_view(template_name="allauth/account/login.html"),
        name="login",
    ),
    path(
        "accounts/signup/",
        users_views.SignUpView.as_view(template_name="allauth/account/signup.html"),
        name="signup",
    ),
    path(
        "accounts/logout/",
        auth_views.LogoutView.as_view(template_name="allauth/account/logout.html"),
        name="logout",
    ),
    path(
        "accounts/password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="allauth/account/password_reset.html"
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="allauth/account/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="allauth/account/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("", include("toolpage.urls")),
    path("", include("Custom_User_Settings.urls", namespace="list-settings")),
]

urlpatterns += [
    path("", include("SavedUserTemplates.urls", namespace="SavedUserTemplate")),
]

# Allauth
urlpatterns += [
    path("accounts/", include("allauth.urls")),
]

toolpage/urls.py
from django.urls import path
from toolpage import views as toolpage_views

app_name = "toolpage"

urlpatterns = [
    path(
        "toolpage_app/", toolpage_views.ToolpageAppView.as_view(), name="toolpage_app"
    ),
    path(
        "toolpage_update/",
        toolpage_views.ToolpageTemplateUpdate.as_view(),
        name="toolpage_template_update",
    ),
    path(
        "reshape/",
        toolpage_views.ReshapeText,
        name="toolpage_reshape",
    ),
    path(
        "readfile/",
        toolpage_views.readfile,
        name="toolpage_readfile",
    ),
    path(
        "transcribe_audio/",
        toolpage_views.transcribe_audio,
        name="toolpage_transcribe_audio",
    ),
]

users/urls.py
"""Accounts app URL Configuration."""

from django.urls import path

from users import views as users_views
from . import views

app_name = "users"

urlpatterns = [
    path(
        "signup/",
        users_views.SignUpView.as_view(success_url="/toolpage_app/"),
        name="signup",
    ),
    path("activate/<uidb64>/<token>", views.activate, name="activate"),
]

toolpage/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class ToolpageTemplate(models.Model):
    # User Profile
    user = models.OneToOneField(
        "users.CustomUser", on_delete=models.CASCADE, null=True, blank=True
    )
    # Voices
    summary = models.BooleanField(default=False)
    formal = models.BooleanField(default=False)
    academic = models.BooleanField(default=False)
    creative = models.BooleanField(default=False)
    study_notes = models.BooleanField(default=False)
    meeting_notes = models.BooleanField(default=False)
    email_and_memo = models.BooleanField(default=False)
    outline = models.BooleanField(default=False)
    story_telling = models.BooleanField(default=False)
    research_paper = models.BooleanField(default=False)
    report = models.BooleanField(default=False)
    resume = models.BooleanField(default=False)
    bionic_reading = models.BooleanField(default=False)

    def __str__(self) -> str:
        return str(self.user)


# Automatically make a saved template when a user makes an account
@receiver(post_save, sender="users.CustomUser")
def create_toolpage_template(sender, instance, created, **kwargs):
    """Used to automatically create a toolpage template."""
    if sender and created:
        ToolpageTemplate.objects.create(user=instance)


# Automation for connecting a toolpage template to the userprofile it belongs to
post_save.connect(create_toolpage_template, sender="users.CustomUser")

toolpage/forms.py
from django import forms
from .models import ToolpageTemplate
from SavedUserTemplates.models import SavedUserTemplate


class ToolpageTemplateForm(forms.ModelForm):
    class Meta:
        model = ToolpageTemplate
        exclude = ["user"]


class ToolpageSavedUserTemplateForm(forms.Form):
    class Meta:
        model = SavedUserTemplate
        exclude = [""]

toolpage/views.py
import json
import os.path
import os
import re
import tempfile
from datetime import timedelta
from html import escape as html_escape

from django.http import HttpResponse, JsonResponse, StreamingHttpResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View
from django.views.decorators.csrf import csrf_exempt

# GenAI
import google.generativeai as genai
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow


# for file conversion
import pypandoc
from pypdf import PdfReader

# Speech Recognition
import speech_recognition as sr
from pydub import AudioSegment

from Custom_User_Settings.models import Custom_User_Settings
from SavedUserTemplates.models import SavedUserTemplate
from user_profile import mixins as user_mixins

from .forms import ToolpageTemplateForm
from .models import ToolpageTemplate


SCOPES = ["https://www.googleapis.com/auth/generative-language.retriever"]


def load_creds():
    """Converts `client_secret.json` to a credential object.

    This function caches the generated tokens to minimize the use of the
    consent screen.
    """
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists("token.json"):
        creds = Credentials.from_authorized_user_file("token.json", SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except Exception as e:
                print(e)
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                "toolpage/client_secret.json", SCOPES
            )
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open("token.json", "w") as token:
            token.write(creds.to_json())
    return creds


class ToolpageAppView(user_mixins.UserProfileRequiredMixin, View):
    template_name = "toolpage/toolpage_app.html"

    def get(self, request, *args, **kwargs):
        current_user_template = ToolpageTemplate.objects.filter(
            user=request.user
        ).first()
        toolpage_template_form: ToolpageTemplateForm = None

        user_settings, created = Custom_User_Settings.objects.get_or_create(
            user_settings=request.user
        )

        if user_settings.retain_last_used_options:
            toolpage_template_form = ToolpageTemplateForm(
                initial={
                    "summary": current_user_template.summary,
                    "formal": current_user_template.formal,
                    "academic": current_user_template.academic,
                    "creative": current_user_template.creative,
                    "study_notes": current_user_template.study_notes,
                    "meeting_notes": current_user_template.meeting_notes,
                    "email_and_memo": current_user_template.email_and_memo,
                    "outline": current_user_template.outline,
                    "story_telling": current_user_template.story_telling,
                    "research_paper": current_user_template.research_paper,
                    "report": current_user_template.report,
                    "resume": current_user_template.resume,
                    "bionic_reading": current_user_template.bionic_reading,
                }
            )
        else:
            toolpage_template_form = ToolpageTemplateForm(
                initial={
                    "summary": False,
                    "formal": False,
                    "academic": False,
                    "creative": False,
                    "study_notes": False,
                    "meeting_notes": False,
                    "email_and_memo": False,
                    "outline": False,
                    "story_telling": False,
                    "research_paper": False,
                    "report": False,
                    "resume": False,
                    "bionic_reading": False,
                }
            )

        rendered_toolpage_template_form = toolpage_template_form.render(
            "toolpage/form_current_template.html"
        )

        saved_user_template = SavedUserTemplate.objects.filter(author=request.user)
        rendered_saved_user_template_form = render(
            request,
            "toolpage/form_saved_template.html",
            {"user_templates": saved_user_template},
        ).content.decode("utf-8")

        context = {
            "toolpage_template_form": rendered_toolpage_template_form,
            "saved_user_template_loader": rendered_saved_user_template_form,
        }

        return render(request, self.template_name, context)


class ToolpageTemplateUpdate(View):

    def post(self, request, *args, **kwargs):
        form = ToolpageTemplateForm(request.POST)
        if form.is_valid():
            user_object = ToolpageTemplate.objects.filter(user=request.user).first()
            form = ToolpageTemplateForm(instance=user_object, data=request.POST)
            form.save()
            data = {"message": "Form saved successfully!"}
            return HttpResponse(json.dumps(data), content_type="application/json")
        else:
            return HttpResponse(
                json.dumps({"message": "Form is not valid"}),
                content_type="application/json",
            )


def generate_error(error_type: str):
    error_messages = {
        "no_options": "ERR: Please select at least one option.",
        "short": "ERR: Please try again with a longer text. Minimum length is 10 words.",
        "length_no_acct": "ERR: Text length is too long. Sign up or log in to increase the limit.",
        "length_free": "ERR: Text length is too long. Please try again with a shorter text, or upgrade to Aluminotes Premium.",
        "length_premium": "ERR: Text length is too long. Please try again with a shorter text.",
        "query_limit": "ERR: Query limit reached. Please try again later.",
        "query_limit_no_acct": "ERR: Query limit reached. Sign up or log in to increase the limit.",
        "vulgar": "ERR: Please remove any vulgar language.",
        "unknown": "ERR: An unknown error occurred.",
    }
    print(error_messages[error_type])
    yield json.dumps(error_messages[error_type])


def ReshapeText(request):
    try:
        if request.method != "POST":
            return JsonResponse({"error": "Invalid request method"}, status=400)
        data = json.loads(request.body)
        prompt = html_escape(data.get("prompt"))
        bionic_reading_check = data.get("bionic_reading_check")
        profile = request.user.userprofile

        prompt_length = len(prompt.split(" "))

        # Error Checking
        print("error checking")
        if prompt[0] == ":" and not bionic_reading_check:
            return StreamingHttpResponse(
                generate_error("no_options"), content_type="text/event-stream"
            )
        if prompt_length < 10:
            return StreamingHttpResponse(
                generate_error("short"), content_type="text/event-stream"
            )

        if profile.user_type == 2:  # No account. CHANGE AS NEEDED
            if prompt_length > 250:
                return StreamingHttpResponse(
                    generate_error("length_no_acct"), content_type="text/event-stream"
                )
            if (timezone.now() - profile.last_prompt_time) < timedelta(seconds=30):
                return StreamingHttpResponse(
                    generate_error("query_limit_no_acct"),
                    content_type="text/event-stream",
                )

        if profile.user_type == 0:  # Free user
            if prompt_length > 500:
                return StreamingHttpResponse(
                    generate_error("length_free"), content_type="text/event-stream"
                )
            if (timezone.now() - profile.last_prompt_time) < timedelta(seconds=12):
                return StreamingHttpResponse(
                    generate_error("query_limit"), content_type="text/event-stream"
                )

        elif profile.user_type == 1:  # Premium user
            if prompt_length > 8000:
                return StreamingHttpResponse(
                    generate_error("length_premium"), content_type="text/event-stream"
                )
            if (timezone.now() - profile.last_prompt_time) < timedelta(seconds=6):
                return StreamingHttpResponse(
                    generate_error("query_limit"), content_type="text/event-stream"
                )

        profile.last_prompt_time = timezone.now()
        profile.save()

        # if no errors, continue as normal
        creds = load_creds()
        genai.configure(credentials=creds)
        # It blocks too much stuff apparently
        unsafe_settings = [
            {
                "category": "HARM_CATEGORY_DANGEROUS",
                "threshold": "BLOCK_NONE",
            },
            {
                "category": "HARM_CATEGORY_HARASSMENT",
                "threshold": "BLOCK_MEDIUM_AND_ABOVE",
            },
            {
                "category": "HARM_CATEGORY_HATE_SPEECH",
                "threshold": "BLOCK_MEDIUM_AND_ABOVE",
            },
            {
                "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
                "threshold": "BLOCK_MEDIUM_AND_ABOVE",
            },
            {
                "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
                "threshold": "BLOCK_NONE",
            },
        ]
        model = genai.GenerativeModel("REDACTED")

        result = model.generate_content(
            prompt, stream=True, safety_settings=unsafe_settings
        )

toolpage/templates/toolpage/app_generic.html
{# Load the tag library #}
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="us-en">
    <head>
        <style>@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap');</style>
        <meta charset="UTF-8" />
        <meta name="description" content="Aluminotes" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="John Doe" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon"
              type="image/png"
              href="{% static 'img/favicon.ico' %}" />
        <title>Aluminotes</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}"
              rel="stylesheet"
              type="text/css" />
        {% block style %}
        {% endblock style %}
    </head>
    {% if user.is_authenticated %}
        <body class="{{ user.custom_user_settings.theme }}">
        {% else %}
            <body class="galactic_blood">
            {% endif %}
            {% include "navbar.html" %}
            <div class="container">
                <h1 class="text-center fw-bold mb-5">
                    {% block title %}
                    {% endblock title %}
                </h1>
                <div>
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
            <!--{% include "footer.html" %}-->
        </body>
    </html>

toolpage/templates/toolpage/form_current_template.html
<div class="options-form">
    {% for field in form %}
        {% if field.label == "Summary" %}
            <div class="text-style">
                <strong>Summarize</strong>
                <br>
                <i>Summarize your notes</i>
                <br>
            </div>
        {% endif %}
        {% if field.label == "Formal" %}
            <hr>
            <div class="text-style">
                <strong>Tone</strong>
                <br>
                <i>Change the tone</i>
                <br>
            </div>
        {% endif %}
        {% if field.label == "Study notes" %}
            <hr>
            <div class="text-style">
                <strong>Format</strong>
                <br>
                <i>Change the formatting</i>
                <br>
            </div>
        {% endif %}
        {% if field.label == "Bionic reading" %}
            <hr>
            <div class="text-style">
                <strong>Accessibility</strong>
                <br>
                <i>Change display settings</i>
                <br>
            </div>
        {% endif %}
        <div class="form-check form-switch checkbox">
            <input class="form-check-input"
                   type="checkbox"
                   role="switch"
                   id="{{ field.name }}"
                   name="{{ field.name }}"
                   onclick="syncOptions()"
                   {% if field.value == True %}checked{% endif %}>
            <label class="form-check-label" for="flexSwitchCheckChecked">{{ field.label }}</label>
        </div>
    {% endfor %}
</div>

toolpage/templates/toolpage/form_saved_template.html
<div class="options-form">
    <div class="text-style">
        <strong>Saved Templates</strong>
        <br>
        <hr>
    </div>
    {% if user_templates %}
        {% csrf_token %}
        {% for saved_user_template in user_templates %}
            <div class="form-check form-switch checkbox">
                <input class="form-check-input saved_user_template_slider"
                       type="radio"
                       id="{{ saved_user_template.name_of_template }}"
                       name="saved_user_template"
                       value="{{ saved_user_template.summary }} {{ saved_user_template.formal }} {{ saved_user_template.academic }} {{ saved_user_template.creative }} {{ saved_user_template.study_notes }} {{ saved_user_template.meeting_notes }} {{ saved_user_template.email_and_memo }} {{ saved_user_template.outline }} {{ saved_user_template.story_telling }} {{ saved_user_template.research_paper }} {{ saved_user_template.report }} {{ saved_user_template.resume }}">
                <label class="form-check-label" for="flexSwitchCheckChecked">{{ saved_user_template.name_of_template }}</label>
            </div>
        {% endfor %}
    {% else %}
        <p>No saved user templates yet.</p>
    {% endif %}
</div>

toolpage/templates/toolpage/toolpage_app copy.html
{% extends "toolpage/toolpage_style.html" %}
{% load static %}
{% block style %}
  <link rel="stylesheet"
        href="{% static 'css/toolpage.css' %}?{{ user.custom_user_settings.theme }}" />
{% endblock style %}
{% block body_start %}
  <body class="apptheme"></body>
{% endblock body_start %}
{% block content %}
  <!--page layout-->
  <!--The option box-->
  <div class="toolpage_main">
    <div class="container option_container">
      <form id="myForm"
            action="."
            method="post"
            class="bloodbackground option_box">
        {% csrf_token %}
        {{ toolpage_template_form }}
        <div>
          <input type="hidden" id="form-data" name="form_data">
        </div>
      </form>
    </div>
    <!--The textboxes-->
    <div class="container text_container">
      <!--Input-->
      {% if user.userprofile.user_type == 1 %}
        <div class="container settings_container">
          <div class="input_text_box">
            <textarea class="bloodbackground input_text_box no_outline_textarea {{ user.custom_user_settings.theme }}_text"
                      placeholder="write here"
                      id="input_text"></textarea>
          </div>
        </div>
        <div class="middle-buttons">
          <div class="media-controls">
            <div class="media-buttons">
              <button class="play-button media-button" label="play">
                <i class="fas fa-play button-icons delta"></i>
                <span class="button-text milli"></span>
              </button>
              <!-- Add other media buttons as needed -->
            </div>
            <audio id="audio_player">
              <source id="audio_source" type="audio/mpeg">
              Your browser does not support the audio element.
            </audio>
          </div>
          <button type="submit"
                  value="Submit"
                  class="fa-sharp fa-solid fa-arrows-rotate generate-button"
                  id="gen_button"></button>
          <div>
            <a id="upload" class="upload-download">
              <i class="fas fa-upload button-icons delta"></i></a>
          </div>
          <div>
            <a id="download" class="upload-download">
              <i class="fas fa-download button-icons delta"></i></a>
          </div>
          <div id="filenameModal" class="modal">
            <div class="modal-content">
              <span class="close">&times;</span>
              <h2>Save Note</h2>
              <p>Enter File Name:</p>
              <input type="text" id="filenameInput">
              <button id="saveFilename">Save</button>
            </div>
          </div>
        </div>
        <!--Output-->
        <div class="output_text_box">
          <p class="bloodbackground output_text_box" id="output_text"></p>
        </div>
      {% elif user.userprofile.user_type == 0 %}
        <textarea class="bloodbackground input_text_box_free no_outline_textarea {{ user.custom_user_settings.theme }}_text"
                  placeholder="write here"
                  id="input_text"></textarea>
        <div>
          <div class="media-controls-free">
            <div class="media-buttons">
              <button class="play-button media-button" label="play">
                <i class="fas fa-play button-icons delta"></i>
                <span class="button-text milli"></span>
              </button>
              <!-- Add other media buttons as needed -->
            </div>
            <audio id="audio_player">
              <source id="audio_source" type="audio/mpeg">
              Your browser does not support the audio element.
            </audio>
          </div>
          <button type="submit"
                  value="Submit"
                  class="fa-sharp fa-solid fa-arrows-rotate generate-button-free"
                  id="gen_button"></button>
        </div>
        <!--Output-->
        <p class="bloodbackground output_text_box_free {{ user.custom_user_settings.theme }}_text"
           id="output_text"></p>
      {% endif %}
      {% if user.userprofile.user_type == 1 %}
        <form id="savedForm"
              action="."
              method="post"
              class="bloodbackground settings_box">
          {{ saved_user_template_loader | safe }}
          <input type="hidden" id="form-data" name="form_data">
          <div class="templates-button-container">
            <a id="template-button"
               class="edit-templates"
               href="{% url 'SavedUserTemplates:list-templates' %}">Templates</a>
          </div>
        </form>
      </div>
      <div class="alert_box alert_box_error" id="alert_box"></div>
    </div>
  {% endif %}
  <!--javascript-->
  <!-- ERRORS & ALERT -->
  <script type="text/javascript" src="{% static '/js/alert_box.js' %}"></script>
  <!--Rotate Generate Button on Click-->
  <script type="text/javascript" src="{% static '/js/rotate_on_click.js' %}"></script>
  <!--Submit without reload-->
  <script type="text/javascript"
          src="{% static '/js/submit_without_reload.js' %}"></script>
  <!-- JavaScript for disabling/enabling sliders -->
  <script type ="text/javascript" src="{% static '/js/slider_enable.js' %}"></script>
  <!--Importing Gemini API-->
  <script type="importmap">
      {
        "imports": {
          "@google/generative-ai": "https://esm.run/@google/generative-ai"
        }
      }
  </script>
  <!--Importing Markdown Converter-->
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <!--Gemini Generator-->
  <script type="text/javascript" src="{% static '/js/gemini_generation.js' %}"></script>
  <!-- JavaScript for text-to-speech -->
  <script type="text/javascript" src="{% static '/js/text_to_speech.js' %}"></script>
  <!-- JavaScript for file upload/download -->
  <!-- UPLOAD -->
  <script type="text/javascript" src="{% static '/js/upload_files.js' %}"></script>
  <!-- DOWNLOAD -->
  <script type="text/javascript" src="{% static '/js/download_files.js' %}"></script>
{% endblock content %}

toolpage/templates/toolpage/toolpage_style.html
{% extends "base_generic.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/toolpage.css' %}" />
{% endblock style %}